image: node:12

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

stages:
  - test
  - build
  - deploy

before_script:
  - yarn install
  - yarn run lerna bootstrap

test:
  stage: test
  script:
    - yarn run lint
    - yarn run build
    - yarn test

publish:
  stage: build
  script:
    - yarn run build
    - yarn run publish:docs
  artifacts:
    paths:
      - demo/dist
      - dist/storybook
      - dist/docs

pages:
  stage: deploy
  except:
    - /^feature/.*/
  script:
    - mv dist/docs public
    # - mv dist/storybook public/storybook
    - mv demo/dist public/demo
  artifacts:
    paths:
      - public

deploy_to_nexus:
  stage: deploy
  except:
    - /^feature/.*/
  script:
    - yarn run build
    - yarn config set $REPO_URL:_authToken=$NPM_AUTH_TOKEN
    - git checkout yarn.lock # --no-git-reset does not work
    - yarn run lerna publish from-package --registry $REPO_URL --yes
