image: node:11.9

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

stages:
  - review
  - test
  - build
  - deploy

before_script:
  - npm install
  - npx lerna bootstrap

lint:
  stage: review
  script:
    - npm run lint

test:
  stage: test
  script:
    - npm run build
    - npm test

publish:
  stage: build
  script:
    - npm run build
    - npm run publish
  artifacts:
    paths:
      - demo/dist
      - dist/storybook
      - dist/docs

pages:
  stage: deploy
  script:
    - mv dist/docs public
    - mv dist/storybook public/storybook
    - mv demo/dist public/demo
  artifacts:
    paths:
      - public

deploy_to_nexus:
  stage: deploy
  script:
  - npm run build
  - npm config set $REPO_URL:_authToken=$NPM_AUTH_TOKEN
  - git checkout package-lock.json # --no-git-reset does not work
  - npx lerna publish from-package --registry $REPO_URL --yes
