name: Publish packages to NPM

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: yarn run lerna bootstrap
      - run: yarn run lint
      - run: yarn run build
      - run: yarn test
      - run: git checkout examples/complexdemo/yarn.lock
      - run: yarn run lerna publish from-package --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
